# numpy函数扫盲计划

In [2]:
import numpy as np

np.array() 实现创建数组，所有数默认使用np.float64，可以使用dtype来指定

In [3]:
a = np.array([1,2,3,4,5])
print(a, type(a), type(a[0]))

[1 2 3 4 5] <class 'numpy.ndarray'> <class 'numpy.int64'>


In [ ]:
b = np.zeros(shape=(3,2)) # 三行两列
print(b, type(b), type(b[0]))

[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
c = np.ones_like(b, dtype=np.float16)
print(b, type(b), type(b[0]))

[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
a.shape, b.shape, c.shape, a.dtype, b.dtype, c.dtype

((5,), (3, 2), (3, 2), dtype('int64'), dtype('float64'), dtype('float16'))

In [7]:
a.ndim, b.ndim, c.ndim, a.size, b.size, c.size

(1, 2, 2, 5, 6, 6)

In [8]:
d = np.arange(start=1, stop=7, step=2)
e = np.arange(1, 7, 2)
print(d, e, d==e)

[1 3 5] [1 3 5] [ True  True  True]


np.linspace返回介于区间内，等分划分的数

In [ ]:
f = np.linspace(start=0, stop=1, num=5) # 参数：起止范围，样本数目
f, f==np.linspace(0,1,5)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([ True,  True,  True,  True,  True]))

np.random.rand() 生成0到1高斯分布的随机数组

In [11]:
tmp = np.random.rand(3,2,2)
tmp, tmp.shape, tmp.dtype

(array([[[0.34160378, 0.46456715],
         [0.70660702, 0.09299822]],
 
        [[0.15350522, 0.80011618],
         [0.91194822, 0.57543497]],
 
        [[0.37476146, 0.80179824],
         [0.30522022, 0.61049298]]]),
 (3, 2, 2),
 dtype('float64'))

对已经构建了的数组，可以使用astype(数据类型)，在新空间中开辟

In [12]:
tmp = b.astype(int)
print(b, tmp, b.dtype, tmp.dtype)
tmp = b.astype(np.uint8)
print(b, tmp, b.dtype, tmp.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]] [[0 0]
 [0 0]
 [0 0]] float64 int64
[[0. 0.]
 [0. 0.]
 [0. 0.]] [[0 0]
 [0 0]
 [0 0]] float64 uint8


## Numpy中的数据运算

相同尺寸的数组可以直接进行四则运算

In [ ]:
a = np.random.rand(2,3)
b = np.random.rand(2,3)
a, b, a+b, a-b, a*b, a/b, a//b, a%b  # 对应元素进行运算

(array([[0.4553048 , 0.93284763, 0.56239008],
        [0.98680338, 0.98293362, 0.13112637]]),
 array([[0.53026546, 0.75184137, 0.24633066],
        [0.89220633, 0.14901671, 0.32973442]]),
 array([[0.98557026, 1.684689  , 0.80872073],
        [1.87900971, 1.13195033, 0.46086078]]),
 array([[-0.07496065,  0.18100626,  0.31605942],
        [ 0.09459704,  0.83391691, -0.19860805]]),
 array([[0.24143241, 0.70135344, 0.13853392],
        [0.88043222, 0.14647354, 0.04323688]]),
 array([[0.85863561, 1.2407506 , 2.28306978],
        [1.10602597, 6.59613007, 0.39767267]]),
 array([[0., 1., 2.],
        [1., 6., 0.]]),
 array([[0.4553048 , 0.18100626, 0.06972876],
        [0.09459704, 0.08883334, 0.13112637]]))

np.dot实现点积运算；@实现矩阵乘法

In [14]:
a = np.random.randint(0, 6, size=(3,3))
b = np.random.randint(0, 6, size=(3,3))
a, b, np.dot(a, b), a@b, np.matmul(a, b), a@b == np.matmul(a, b)

(array([[4, 5, 4],
        [4, 2, 1],
        [3, 5, 4]]),
 array([[3, 0, 5],
        [4, 5, 2],
        [4, 3, 1]]),
 array([[48, 37, 34],
        [24, 13, 25],
        [45, 37, 29]]),
 array([[48, 37, 34],
        [24, 13, 25],
        [45, 37, 29]]),
 array([[48, 37, 34],
        [24, 13, 25],
        [45, 37, 29]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

np.sqrt实现求平方根
np.sin, np.cos实现三角运算
np.log，np.power实现对数和指数运算

In [19]:
a = np.random.randint(1, 5, size=(1, 3))
a, np.sqrt(a), np.sin(a), np.cos(a)

(array([[3, 2, 3]]),
 array([[1.73205081, 1.41421356, 1.73205081]]),
 array([[0.14112001, 0.90929743, 0.14112001]]),
 array([[-0.9899925 , -0.41614684, -0.9899925 ]]))

In [20]:
np.log(a), np.power(a, 2)

(array([[1.09861229, 0.69314718, 1.09861229]]), array([[9, 4, 9]]))

如果把narry和一个数进行四则运算，那么所有元素都会进行四则运算，这是广播机制

四则运算永远是对应元素之间的计算，和矩阵乘法要区分开

In [21]:
a = np.random.randint(1, 30, size=(2,3))
a, a*5, a+5, a-5, a/5, a//5, a%5

(array([[ 3, 29, 23],
        [17, 14,  1]]),
 array([[ 15, 145, 115],
        [ 85,  70,   5]]),
 array([[ 8, 34, 28],
        [22, 19,  6]]),
 array([[-2, 24, 18],
        [12,  9, -4]]),
 array([[0.6, 5.8, 4.6],
        [3.4, 2.8, 0.2]]),
 array([[0, 5, 4],
        [3, 2, 0]]),
 array([[3, 4, 3],
        [2, 4, 1]]))

广播的另一个特点：如果两个数组的shape不一致，会把数组放缩为一致的shape，然后再运算

广播的前提：
NumPy 在判断两个数组是否兼容时，会比较它们的每一个维度（从最右边的维度开始往前比）。
两个维度兼容的条件只有两个：

该维度的大小相等。

其中一个维度的大小为 1。

In [23]:
a = np.array([1,2,3])
b = np.arange(start=4,stop=7).reshape((3,1))
a, b, a+b, a*b, a/b, a//b, a%b

(array([1, 2, 3]),
 array([[4],
        [5],
        [6]]),
 array([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]),
 array([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]]),
 array([[0.25      , 0.5       , 0.75      ],
        [0.2       , 0.4       , 0.6       ],
        [0.16666667, 0.33333333, 0.5       ]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]))

In [ ]:
# 那如果是2*3和3*2呢，会直接报错
a = np.arange(start=1, stop=7).reshape((2,3))
b = np.arange(start=-6,stop=0).reshape((3,2))
a, b, a+b, a-b, a*b, a/b, a//b, a%b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## min, max, argmin, argmax操作

如果都不加axis参数，就会把一个多维数组降维为一维后，从全局视角出发返回最值/最值的索引

如果加axis参数，相当于消去当前参数对应的维度，比如假设原始为(2,3)矩阵，加上axis=0，就消去了0号维度，变成(3,)，此时返回的最值/最值索引就是一行三列元素；如果axis=1，消去了1号维度，变成(2,)，此时返回的最值/最值索引就是一行两列元素。

In [25]:
a, b, a.min(), b.min(), a.max(), b.max()

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[-6, -5],
        [-4, -3],
        [-2, -1]]),
 1,
 -6,
 6,
 -1)

In [26]:
a.min(axis=0), a.min(axis=1)

(array([1, 2, 3]), array([1, 4]))

In [27]:
a.argmax(), a.argmax(axis=0), a.argmax(axis=1), a.argmin(), a.argmin(axis=0), a.argmin(axis=1)

(5, array([1, 1, 1]), array([2, 2]), 0, array([0, 0, 0]), array([0, 0]))

In [28]:
a = np.random.randint(1, 100, size=(2,3))

In [29]:
a, a.argmax(), a.argmax(axis=0), a.argmax(axis=1), a.argmin(), a.argmin(axis=0), a.argmin(axis=1)

(array([[92, 62, 10],
        [78, 10, 15]]),
 0,
 array([0, 0, 1]),
 array([0, 0]),
 2,
 array([1, 1, 0]),
 array([2, 1]))

(array([[92, 62, 10],
        [78, 10, 15]]),
 0,
 array([0, 0, 1]),
 array([0, 0]),
 2,
 array([1, 1, 0]),
 array([2, 1]))
 
 上一个结果的解释：全局最大0号元素，最小2号元素（铺平展开）

 axis=0视角下，每一列的最大元素索引分别为0，0，1；每一列的最小索引分别为1，1，0

 axis=1视角下，每一行的最大元素索引分别为0，0；每一行的最小索引分别为2，1

求和  a.sum([axis=])

均值 a.mean([axis=]);np.median(a, [axis=])

方差 a.var([axis=])

标准差 a.std([axis=])

In [30]:
a, a.sum(), a.sum(axis=0), a.sum(axis=1), a.mean(), a.mean(axis=0), a.mean(axis=1)

(array([[92, 62, 10],
        [78, 10, 15]]),
 267,
 array([170,  72,  25]),
 array([164, 103]),
 44.5,
 array([85. , 36. , 12.5]),
 array([54.66666667, 34.33333333]))

In [31]:
np.median(a, axis=0)

array([85. , 36. , 12.5])

In [32]:
a, a.var(), a.var(axis=0), a.std(), a.std(axis=0)

(array([[92, 62, 10],
        [78, 10, 15]]),
 1155.9166666666667,
 array([ 49.  , 676.  ,   6.25]),
 33.99877448771745,
 array([ 7. , 26. ,  2.5]))

使用下标访问元素a[i, j], 也可以用原始的list方式访问a[i][j]

通过条件筛选指定的元素a[a<3]，行优先，最终返回一个一维数组

In [33]:
a, a[0,1], a[0][1], a[a<40]

(array([[92, 62, 10],
        [78, 10, 15]]),
 62,
 62,
 array([10, 10, 15]))

In [35]:
# 可以使用逻辑运算符组合不同的条件
# 区分原生的与或操作，这里用单一单符号
a[ (a<40) & (a%2==1)], a[(a<40)|(a%2==0)]

(array([15]), array([92, 62, 10, 78, 10, 15]))

切片操作，和原生的list用法一致，但是可以在一个方括号里面用逗号分隔

In [37]:
a[0][0:2], a[0, 0:2]

(array([92, 62]), array([92, 62]))

In [38]:
a[0], a[0, :]

(array([92, 62, 10]), array([92, 62, 10]))

In [39]:
# 冒号后面可以再来一个冒号，表明跨度stride
a[0, ::2]

array([92, 10])

In [40]:
a[0, ::-1], a[0, ::-2]

(array([10, 62, 92]), array([10, 92]))

In [41]:
a, a[::-1]

(array([[92, 62, 10],
        [78, 10, 15]]),
 array([[78, 10, 15],
        [92, 62, 10]]))