## pytorch函数扫盲计划

In [1]:
import torch

### torch.arange

用于创建一个**一维张量（Tensor）**，其值是一个**等差数列**。

In [9]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [10]:
torch.arange(1.0, 3.0, 0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000])

In [11]:
torch.arange(5,1, -0.5)

tensor([5.0000, 4.5000, 4.0000, 3.5000, 3.0000, 2.5000, 2.0000, 1.5000])

### torch.outer

- **功能：** 计算两个一维张量（向量）的外积。
- **输入：** 两个一维张量 `input` (长度 $N$) 和 `vec2` (长度 $M$)。
- **输出：** 一个二维张量（矩阵），形状为 $(N, M)$。
- **计算：** 输出矩阵的 `[i, j]` 元素等于 `input[i] * vec2[j]`。

In [12]:
v1 = torch.arange(1,4)
v2 = torch.arange(1,3)
print(v1, v2)
torch.outer(v1, v2)

tensor([1, 2, 3]) tensor([1, 2])


tensor([[1, 2],
        [2, 4],
        [3, 6]])

In [13]:
torch.outer(v2, v1)

tensor([[1, 2, 3],
        [2, 4, 6]])

### torch.where

- **功能：** 这是一个三元运算符，类似 `if/else`，但是是元素级别的。
- **签名：** `torch.where(condition, x, y)`
- **输入：**
    - `condition`：一个布尔型张量（包含 `True` 和 `False`）。
    - `x`：当条件为 `True` 时，从中取值的张量。
    - `y`：当条件为 `False` 时，从中取值的张量。
- **输出：** 一个新的张量，其元素根据 `condition` 从 `x` 或 `y` 中选择。

In [14]:
x = torch.arange(1,6,1)
y = torch.arange(10,60, 10)
condition = (x>3)
torch.where(condition, x, y)

tensor([10, 20, 30,  4,  5])

In [15]:
torch.where(condition, y, x)

tensor([ 1,  2,  3, 40, 50])

In [ ]:
x = torch.arange(1,5,1) # 1,2,3,4
y = torch.arange(10,60, 10)
condition = (x>3)
torch.where(condition, x, y) # 必须维度一致

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [23]:
# 如果是高纬向量呢
x = torch.tensor([[1,2],
                 [3,4]])
y = torch.tensor([[10,20],
                 [30,40]])
x.shape, y.shape
torch.where(x>2, x, y)
condition = (x>3)
torch.where(condition, x, y)

tensor([[10, 20],
        [30,  4]])

### torch.cat

- **功能：** 沿着一个指定的维度（dimension）将多个张量拼接（连接）在一起。
- **签名：** `torch.cat(tensors, dim=0)`
- **输入：**
    - `tensors`：一个包含多个张量的列表或元组。
    - `dim`：要拼接的维度（轴）。
- **要求：** 除了 `dim` 维度之外，所有其他维度的大小必须完全相同。

In [31]:
x = torch.rand((2,3))
y = torch.randint(0,20,(2,3))

In [32]:
x,y

(tensor([[0.6691, 0.8728, 0.0952],
         [0.4736, 0.4726, 0.2169]]),
 tensor([[ 0, 12,  7],
         [10,  2,  6]]))

In [33]:
torch.cat([x, y], dim=0)

tensor([[ 0.6691,  0.8728,  0.0952],
        [ 0.4736,  0.4726,  0.2169],
        [ 0.0000, 12.0000,  7.0000],
        [10.0000,  2.0000,  6.0000]])

In [34]:
torch.cat([x,y],dim=-1)

tensor([[ 0.6691,  0.8728,  0.0952,  0.0000, 12.0000,  7.0000],
        [ 0.4736,  0.4726,  0.2169, 10.0000,  2.0000,  6.0000]])

### torch.cos

- **功能：** 逐元素（element-wise）计算输入张量中每个元素的余弦值。
- **输入：** 一个张量（输入值被视为弧度）。
- **输出：** 一个形状相同的新张量，包含计算结果。

### torch.sin

- **功能：** 逐元素（element-wise）计算输入张量中每个元素的正弦值。
- **输入：** 一个张量（输入值被视为弧度）。
- **输出：** 一个形状相同的新张量，包含计算结果。

In [35]:
torch.cos(x)

tensor([[0.7844, 0.6427, 0.9955],
        [0.8899, 0.8904, 0.9766]])

In [36]:
torch.cos(y)

tensor([[ 1.0000,  0.8439,  0.7539],
        [-0.8391, -0.4161,  0.9602]])

In [37]:
torch.sin(x), torch.sin(y)

(tensor([[0.6202, 0.7661, 0.0951],
         [0.4561, 0.4552, 0.2152]]),
 tensor([[ 0.0000, -0.5366,  0.6570],
         [-0.5440,  0.9093, -0.2794]]))

### torch.triu

`torch.triu`（**triangular upper** 的缩写）用于 **返回矩阵的上三角部分**，下三角部分可以置为 0。

```python
torch.triu(input, diagonal=0)
```

- **`input`**：输入张量（通常是二维矩阵）。
- **`diagonal`**（默认 0）：
    - 表示从主对角线开始偏移的位置。
    - `diagonal = 0`：保留主对角线及其上方。
    - `diagonal > 0`：上移对角线（更少的元素被保留）。
    - `diagonal < 0`：下移对角线（保留更多元素）。

In [38]:
x = torch.arange(1,10,1)

In [39]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x = x.view(3,3)

In [45]:
torch.triu(x)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])

In [46]:
torch.triu(x, diagonal=1)

tensor([[0, 2, 3],
        [0, 0, 6],
        [0, 0, 0]])

In [47]:
torch.tril(x,0), torch.tril(x,1), torch.tril(x, 2)

(tensor([[1, 0, 0],
         [4, 5, 0],
         [7, 8, 9]]),
 tensor([[1, 2, 0],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [48]:
torch.tril(x,-1)

tensor([[0, 0, 0],
        [4, 0, 0],
        [7, 8, 0]])

### torch.reshape

`torch.reshape` 用于 **改变张量的形状**，但不会改变其数据内容（底层内存保持一致）。

```python
torch.reshape(input, shape)
```

- **`input`**：输入张量。
- **`shape`**：新的形状（tuple 或 list），总元素个数必须与原张量一致。

> 你也可以用 -1 让 PyTorch 自动推断该维度的大小。
>

In [52]:
x = torch.arange(0,20,1)

In [53]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [54]:
x.view(4,-1) == x.reshape(4,-1)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [55]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [56]:
x.reshape(4,-1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [57]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [58]:
y = torch.reshape(x, (5,-1))

In [59]:
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### torch.topk

`torch.top_k(input, k, dim=None, largest=True)`

- `input`: 你的输入张量（例如模型的输出 logits）。
- `k`: 你想找出的元素数量（例如 `k=5` 就是 top-5）。
- `dim`: 沿着哪个维度进行查找。默认是最后一个维度。
- `largest`:
    - `True` (默认): 查找最大的 `k` 个值。
    - `False`: 查找最小的 `k` 个值。

它返回一个包含**两个**张量的命名元组 (named tuple)：

1. `values`: 最大的 `k` 个值。
2. `indices`: 这些值对应的索引。

In [60]:
torch.topk(y, 3, dim=0)

torch.return_types.topk(
values=tensor([[16, 17, 18, 19],
        [12, 13, 14, 15],
        [ 8,  9, 10, 11]]),
indices=tensor([[4, 4, 4, 4],
        [3, 3, 3, 3],
        [2, 2, 2, 2]]))

In [61]:
torch.topk(y, 3, dim=-1)

torch.return_types.topk(
values=tensor([[ 3,  2,  1],
        [ 7,  6,  5],
        [11, 10,  9],
        [15, 14, 13],
        [19, 18, 17]]),
indices=tensor([[3, 2, 1],
        [3, 2, 1],
        [3, 2, 1],
        [3, 2, 1],
        [3, 2, 1]]))

### torch.repeat_interleave

**作用：**

👉 按“元素级别”重复张量里的值（不是整段 repeat）。

### 直觉

> 每个元素复制几份，再按原顺序排好。
>

In [62]:
torch.repeat_interleave(y, repeats=2)

tensor([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
         9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17,
        18, 18, 19, 19])

In [63]:
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [66]:
repeats = torch.tensor([1,2,3])
to_repeat = torch.tensor([2,4,6])
torch.repeat_interleave(to_repeat, repeats)

tensor([2, 4, 4, 6, 6, 6])

### torch.argsort

**作用：**

👉 返回“排序后元素在原数组中的索引”。

### 直觉

> 不告诉你排完的值，告诉你「谁排第几」。
>

In [67]:
a = torch.randint(0, 30, (3,4))
a

tensor([[19,  9,  7,  9],
        [22,  8, 23,  6],
        [15, 22, 24, 10]])

In [68]:
torch.argsort(a)

tensor([[2, 1, 3, 0],
        [3, 1, 0, 2],
        [3, 0, 1, 2]])

In [70]:
torch.argsort(a, dim=0)

tensor([[2, 1, 0, 1],
        [0, 0, 1, 0],
        [1, 2, 2, 2]])

### torch.bincount

**作用：**

👉 统计**非负整数**出现的次数（直方图）。

### 直觉

> “每个数字出现了多少次？”
> 

###

In [71]:
torch.bincount(a)

RuntimeError: bincount only supports 1-d non-negative integral inputs.

In [72]:
torch.bincount(a[0])

tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [73]:
x = torch.tensor([0,1,1,3,2,1])
weights = torch.tensor([1.,1.,1.,2.,1.,1.])
count = torch.bincount(x, weights)
count

tensor([1., 3., 1., 2.])

### torch.div

**作用：**

👉 张量的 **逐元素除法**（element-wise division）。

In [75]:
a = torch.randint(1,4,(3,))
b = torch.randint(2,5,(3,))

In [76]:
a,b,torch.div(a,b)

(tensor([2, 3, 3]), tensor([4, 4, 3]), tensor([0.5000, 0.7500, 1.0000]))

### torch.mean

**作用：**

👉 对张量求**平均值（算术均值）**

In [ ]:
torch.mean(a) # 还必须是浮点数

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [78]:
b = torch.rand((3,4))
b

tensor([[0.5555, 0.9796, 0.9231, 0.5351],
        [0.7897, 0.8628, 0.4036, 0.1723],
        [0.8709, 0.9218, 0.7093, 0.0522]])

In [ ]:
torch.mean(b,dim=0), torch.mean(b, dim=1) # 外层循环是非dim，内层循环是dim指定的，dim就是要消除的维度

(tensor([0.7387, 0.9214, 0.6787, 0.2532]), tensor([0.7483, 0.5571, 0.6386]))

### torch.scatter_add_

**作用：**

👉 按索引，把值**加到目标张量指定位置**（原地操作）。

### 直觉

> “把东西按 index 分桶加进去”。
>

In [80]:
out = torch.zeros(5)
index = torch.tensor([0,1,0,3])
src = torch.tensor([1.,2.,3.,4.])

out.scatter_add_(dim=0, index=index, src=src)
out

tensor([4., 2., 0., 4., 0.])

### nn.Parameter

`nn.Parameter` 是一个**特殊的 `Tensor`**。

它本质上是一个 `Tensor`，但它被 `nn.Parameter` 包装（wrap）后，就有了特殊的含义：

> "我是一个模型的可训练参数（权重或偏置）。"
> 

当你将一个 `nn.Parameter` 赋值给一个 `nn.Module` 的属性时（例如 `self.weight = nn.Parameter(...)`），`nn.Module` 就会自动“注册”它。

`nn.Parameter` 与普通 `Tensor` 的关键区别：

1. **自动注册：** `nn.Parameter` 会被 `nn.Module` 自动添加到 `.parameters()` 列表中。普通的 `Tensor` 不会。
2. **`requires_grad` 默认为 `True`：** 因为参数天生就是需要被训练的，所以它们默认需要计算梯度。

### nn.Module

`nn.Module` 是 PyTorch 中所有神经网络层和模型的**基类（Base Class）**。

当你构建一个模型（例如 `MyModel`）或一个层（例如 `nn.Linear`, `nn.Conv2d`，或者你自己写的 `FeedForward` 层）时，你**必须**继承 `nn.Module`。

`nn.Module` 扮演着一个**容器**的角色，它主要帮你做两件大事：

1. **自动追踪参数 (Parameters)：**
    - 它会自动“注册”所有在 `__init__` 中被定义为 `nn.Parameter` 或**子模块**（其他 `nn.Module`）的属性。
    - 这就是为什么你可以简单地调用 `model.parameters()` 就能获取到模型**所有**的可训练参数（包括所有嵌套子模块的参数），并把它们交给优化器 `torch.optim.Adam(model.parameters())`。
2. **提供核心功能：**
    - 它提供了一系列标准方法，如 `.to(device)`（将模型所有参数移动到 GPU/CPU）、`.train()`（设置为训练模式，激活 Dropout/BN）和 `.eval()`（设置为评估模式，关闭 Dropout/BN）。
    - 它要求你必须实现 `forward()` 方法，这定义了数据（`x`）如何流经你的模块。

### nn.Linear

`nn.Linear` 的唯一作用就是对输入数据 $x$ 执行一次**线性变换**，即应用一个**“权重矩阵” (A) 和一个 “偏置” (b)**。

In [81]:
import torch.nn as nn

In [83]:
tmp = torch.rand((5,4))

In [82]:
layer = nn.Linear(4,10,True) # 4输入 10输出，带有偏执
layer(torch.rand(5,4))

tensor([[ 0.6426, -0.6584,  0.1382, -0.5235, -0.2285, -0.2676,  0.2635,  0.3660,
          0.3844,  0.0112],
        [ 0.6598, -0.8047, -0.0215, -0.5665, -0.3200, -0.2263,  0.3418,  0.4518,
          0.6334,  0.3915],
        [ 0.5682, -0.8046, -0.3053, -0.1197, -0.0790, -0.1596,  0.5169,  0.3494,
          0.5298,  0.5656],
        [ 0.7337, -0.8577, -0.0173, -0.5837, -0.3768, -0.2540,  0.3419,  0.4263,
          0.7082,  0.4046],
        [ 0.8510, -0.8733, -0.1871, -0.2421, -0.2880, -0.3350,  0.4105,  0.1594,
          0.6714,  0.3169]], grad_fn=<AddmmBackward0>)

### nn.Dropout

`nn.Dropout` 层在训练时，会**随机地**将输入张量中的一部分元素**置为零**，同时对剩余的元素进行**放大（scale up）**。

想象一下你有一个张量（比如一层的激活值）：
`input = [1, 2, 3, 4, 5]`

当你创建一个 `nn.Dropout(p=0.5)`（即 50% 的丢弃率）并将其应用到输入上时：

**在 `model.train()` 模式下 (训练时):**
它可能会产生这样的输出（每次都不同）：
`output = [0, 4, 0, 8, 0]`

- `1`, `3`, `5` 被随机选中并置为 `0`。
- `2`, `4` 被保留，但它们被**放大**了。
- **为什么放大？** `nn.Dropout` 会将剩余元素乘以 `1 / (1 - p)`。
    - 在这里 `p=0.5`，所以 `1 / (1 - 0.5) = 2`。
    - `2 * 2 = 4`，`4 * 2 = 8`。
    - 这样做的目的是**保持层激活的总和（期望值）不变**，使得训练和测试时的激活尺度大致相同。

In [84]:
dropout = nn.Dropout(0.1)
tmp, dropout(tmp)

(tensor([[0.7297, 0.0956, 0.2908, 0.4455],
         [0.4558, 0.9777, 0.6981, 0.1958],
         [0.5262, 0.2188, 0.3361, 0.2547],
         [0.2729, 0.0485, 0.7072, 0.5062],
         [0.9356, 0.5284, 0.3381, 0.5782]]),
 tensor([[0.8107, 0.1062, 0.3231, 0.0000],
         [0.5064, 1.0863, 0.0000, 0.2175],
         [0.5847, 0.2431, 0.3735, 0.2830],
         [0.3032, 0.0539, 0.7858, 0.0000],
         [1.0395, 0.5871, 0.3757, 0.6425]]))

### nn.Embedding

- **功能：** 这是一个**查找表 (lookup table)**。
- **作用：** 它的唯一作用是存储一个“词典”的向量。你给它一个**索引 (index)**（一个整数），它返回与该索引对应的**向量 (vector)**。
- **用途：** 这是 NLP（自然语言处理）模型的基石。计算机无法理解单词 "hello"，但我们可以给 "hello" 分配一个 ID，比如 `5`。`nn.Embedding` 层会存储一个向量，当你输入 `5` 时，它就返回这个向量。
- **可训练性：** `nn.Embedding` 内部的整个查找表（一个大矩阵）是一个 `nn.Parameter`，因此它**是可训练的**。在训练过程中，模型会学会（通过反向传播）为 "hello" 找到一个有意义的向量表示。

In [85]:
embedding_layer = nn.Embedding(num_embeddings=1000, embedding_dim=32) # 总共1000个单词，每一个单词用32维表征
input_ids = torch.tensor([[1,5,2,9]],dtype=torch.long)

output_vectors = embedding_layer(input_ids)

In [86]:
output_vectors

tensor([[[ 0.9045, -2.1375, -0.8254, -0.9130,  1.5161,  0.9511, -0.5881,
           0.6197,  1.6764,  0.8725, -0.0215,  0.7426,  1.4229, -0.7929,
           1.1934, -1.4218, -0.4158, -0.0492,  0.5677, -0.5312,  0.1221,
           0.3921,  0.5383, -0.3037, -1.2837, -1.3147,  0.1809,  0.3029,
          -0.5599, -1.4367,  0.1101,  0.1545],
         [-1.1956,  0.8044,  1.6969, -1.9774, -1.9801,  1.0029, -0.1618,
          -0.4602, -0.8067, -0.7668, -0.0817,  0.0398, -0.7872, -1.0401,
           0.7474,  0.2062,  3.3631, -2.7851, -0.7102, -0.6011, -1.8519,
          -1.2623, -1.3169,  0.2221,  0.3282,  0.9246,  0.6605, -0.1928,
           0.0337,  0.4381, -0.0237,  1.1119],
         [ 1.9555, -0.2260, -1.0551,  0.2376,  1.7085,  0.4913,  1.0751,
           1.0956,  0.4558, -1.0066, -0.3913, -1.7340, -1.2177,  2.3718,
          -0.4894,  0.4472, -0.9173,  0.6363,  0.3577,  0.6317,  0.1616,
          -1.0650,  0.7974,  1.1944, -0.6464,  0.9612, -1.0256,  1.0373,
           0.1180,  1.3976,  0

### nn.ModuleList

- **功能：** 一个**可以正确注册模块**的 Python 列表。
- **作用：** `nn.ModuleList` 本身就像一个普通的 Python `list`，你可以 `.append()`、`.extend()` 或迭代它。
- **为什么需要它？**
    - 如果你在一个 `nn.Module` 中使用**普通的 Python 列表**来存储子模块（如 `nn.Linear`），PyTorch 的“系统”（如 `model.parameters()` 或 `model.to(device)`) **无法“看到”** 列表中的模块。
- **`nn.ModuleList` vs `nn.Sequential`**：
    - `nn.Sequential`：也是一个模块容器，但它**自带 `forward`**，会自动按顺序执行层。
    - `nn.ModuleList`：**没有 `forward`**。它只是一个列表。你必须自己在 `forward` 中写 `for` 循环来使用它。当你需要执行复杂逻辑（例如，跳跃连接）时，`ModuleList` 更灵活。

In [ ]:
# 错误写法：
class BadModel(nn.Module):
    def __init__(self):
        super().__init__()
        # PyTorch 无法检测到这两个 Linear 层
        self.layers = [nn.Linear(10, 10), nn.Linear(10, 10)] 
# model.parameters() 会是空的！
# model.to('cuda') 会失败！

# 正确写法：
class GoodModel(nn.Module):
    def __init__(self):
        super().__init__()
        # PyTorch 可以正确注册这两个 Linear 层
        self.layers = nn.ModuleList([nn.Linear(10, 10), nn.Linear(10, 10)]) 

    def forward(self, x):
        # 你必须在 forward 中手动迭代它
        for layer in self.layers:
            x = layer(x)
        return x
# model.parameters() 会包含所有参数
# model.to('cuda') 会正常工作

### nn.Module.register_buffer

- **功能：** 在 `nn.Module` 中注册一个**缓冲区 (buffer)**。
- **作用：** 1. `register_buffer` 让你在模型中保存一个张量（就像 `self.weight` 一样）。
2. 这个张量**不是一个可训练的参数 (Parameter)**。
3. 优化器（如 Adam）**不会**更新它。
- **为什么需要它？**
    - **问题：** 假设你有一个张量（比如一个固定的掩码 `mask`）需要在模型中使用。你不能只写 `self.mask = torch.ones(...)`，因为当你调用 `model.to('cuda')` 时，`self.mask` 会留在 CPU 上，导致设备不匹配错误。
    - **解决方案：** 你使用 `self.register_buffer("mask", torch.ones(...))`。
- **`register_buffer` 的好处：**
    1. **设备持久性：** 当你调用 `model.to(device)` 时，缓冲区（buffer）会**自动**被移动到正确的设备（如 GPU）。
    2. **状态持久性：** 当你调用 `model.state_dict()`（保存模型）时，缓冲区会**自动**被包含在 `state_dict` 中。
    3. **非参数性：** 它**不会**出现在 `model.parameters()` 列表中，因此优化器会忽略它。

**示例：**
在你之前看到的注意力代码中，`causal_mask` 是一个完美的 `register_buffer` 候选者。它在 `forward` 中被创建，但如果你的序列长度固定，你可以在 `__init__` 中创建它。

In [ ]:
class MyAttention(nn.Module):
    def __init__(self, max_len = 512):
        super().__init__()
        mask  = torch.triu(torch.full((max_len, max_len), float('-inf')), diagonal=1).unsqueeze(0).unsqueeze(0)

    def forward(self, x):
        seq_len = x.shape[2]
        scores = x + self.causal_mask[:, :, :seq_len, :seq_len]
        return scores

### torch.nn.utils.clip_grad_norm_

- **梯度裁剪**。这是训练 Transformer（尤其是 LLM）的**必需品**。
- 它防止梯度变得过大（“梯度爆炸”），导致训练不稳定。`clip_grad_norm_` 会检查所有梯度的总范数（L2 范数），如果超过 `args.grad_clip`（例如 1.0），就将它们**按比例缩小**到 1.0。

In [ ]:
torch.nn.utils.clip_grad_norm()

### tensor.transpose

用于**交换 (swap)** 张量的**两个**指定维度。

`output_tensor = tensor.transpose(dim0, dim1)`

- `tensor`：你的输入张量。
- `dim0` (int)：你想要交换的第一个维度的索引。
- `dim1` (int)：你想要交换的第二个维度的索引。

### tensor.view

**在不改变数据内容的前提下，改变张量的“视图”或“维度”**。

**1. 核心功能：重塑形状**

`view()` 允许你指定一个新的形状（维度），PyTorch 会将原始张量的数据“重新填充”到这个新形状中。

**关键要求：** 新形状的总元素数量必须与原始形状的总元素数量**完全相同**。

**2. 特殊参数 `1`：自动推断维度**

在 `view()` 中，你可以将**一个**维度指定为 `-1`。PyTorch 会自动计算该维度的大小，以确保总元素数量不变。

这在处理**批量大小 (batch size)** 时极其有用，因为你可能不知道批量大小具体是多少。

在神经网络中，当数据从卷积层（例如 `(B, C, H, W)`）进入全连接层时，`view(batch_size, -1)` 是最常见的操作，用于将所有特征展平。

---

**3. ⚠️ 关键特性：View (视图)**

这是 `view()` 最重要（也最容易出错）的特性：

`view()` **不会**创建新的内存副本，它返回的是原始张量的一个**视图 (View)**。

- **高效：** 操作非常快，不移动数据，只改变元数据。
- **数据共享：** 修改 `view()` 后的张量**会**改变原始张量的数据。
### 4. `view()` vs `reshape()`

`reshape()` 是一个功能更强大、更“安全”的替代品。

- **`view()`：**
    - **要求：** 必须在**内存连续 (contiguous)** 的张量上才能工作。
    - 如果你对一个张量执行了 `transpose()` 或 `permute()`，它在内存中可能就不连续了，此时调用 `view()` 会**报错**。
    - **例如：** `t.transpose(0, 1).view(-1)` 经常会失败。
- **`reshape()`：**
    - **推荐使用。**
    - 如果张量是内存连续的，它的行为和 `view()` 完全一样（返回一个视图，高效）。
    - 如果张量**不是**内存连续的（比如 `transpose` 之后），`reshape()` 会**自动**创建一个数据副本（返回一个新的张量），以确保操作成功。

**总结：** 除非你非常确定你的张量是连续的，并且追求极致的性能（避免可能的拷贝），否则**优先使用 `reshape()`** 会更安全、更方便。

### tensor.unsqueeze

`tensor.unsqueeze()` 是 PyTorch 中一个用于**增加维度**的操作。

它的功能非常简单：**在张量的指定位置插入一个大小为 1 的新维度**。

`output_tensor = tensor.unsqueeze(dim)`

- `tensor`：你的输入张量。
- `dim` (int)：你想要**插入**新维度的位置（索引）。这个索引的范围可以在 `[-input.dim() - 1, input.dim()]` 之间。

### optimizer.param_groups

`optimizer.param_groups` 是 PyTorch 优化器（如 `AdamW`）内部的一个**列表（list）**。

这个列表中的**每一项**都是一个**字典（dict）**，代表一个**“参数组”**。

### 为什么需要它？

1. **动态修改学习率 (LR) - (这是你代码中的用法)**
    - 在训练过程中，我们经常需要根据 `get_lr` 这样的函数（即学习率调度器）来**动态改变学习率**。
    - 优化器（Optimizer）不知道你的调度器，你必须**手动**告诉它新的学习率。
    - `optimizer.param_groups[0]['lr']` 存储了第一组参数的当前学习率。
    - 你的代码：Python
        
        `for param_group in optimizer.param_groups:
            param_group["lr"] = lr`
        
        这是一个标准做法。它遍历所有参数组（通常只有一个），并将字典中的 `"lr"` 键更新为新计算出的 `lr` 值。在下一次 `optimizer.step()` 时，优化器就会使用这个新 Lr。
        
2. **为不同层设置不同 Lr - (高级用法)**
    - 你也可以在创建优化器时，手动传入多个参数组，每组有不同的 Lr 或 `weight_decay`。
    - 例如：在微调（Finetune）时，你可能想让模型主干（backbone）的学习率很低，而新加的分类头（head）的学习率很高。

> 一句话总结：optimizer.param_groups 是 PyTorch 优化器存储其超参数（尤其是 Lr）的地方。你的代码通过修改它，来实时应用学习率调度器（scheduler）计算出的新 Lr。
>

### scaler.scale

这是**自动混合精度（AMP）训练的核心，用于防止梯度下溢（Gradient Underflow）**。

1. **混合精度 (AMP)**：为了加快训练，我们使用 `autocast_ctx`（自动类型转换上下文），它会将模型的权重和计算（如矩阵乘法）从 `float32`（32位全精度）转换为 `float16`（16位半精度）。`float16` 计算更快，显存占用更少。
2. **问题**：`float16` 的数值范围非常小。在反向传播（`backward()`）时，一些非常小的梯度值（例如 `1e-20`）可能会因为“下溢”而**直接变为 0**。如果梯度变为 0，模型的那部分权重就停止学习了。

### `scaler` 的解决方案 (梯度缩放)

`scaler`（即 `torch.cuda.amp.GradScaler`）通过“放大”和“缩小”来解决这个问题：

1. **`scaler.scale(loss)`：【放大】**
    - 在 `backward()` 之前，`scaler` 将你计算出的 `loss` **乘以一个非常大的缩放因子**（例如 65536.0）。
    - `scaled_loss = loss * 65536.0`
2. **`.backward()`：【在放大后反向传播】**
    - `scaled_loss.backward()`
    - 根据链式法则，所有计算出的梯度也会被**自动放大**同样的倍数（65536.0）。
    - 这样，那个本应是 `1e-20` 的梯度变成了 `1e-20 * 65536.0`，这个值 `float16` 就可以表示了，避免了下溢。

> 一句话总结：scaler.scale(loss).backward() 不是在对 loss 求导，而是对 loss * 缩放因子 求导，以此在 float16 环境下保护微小的梯度值不丢失。
>

In [1]:
import torch
x = torch.tensor([1,2,3,4,5,6])
x.pow(2), x**2

(tensor([ 1,  4,  9, 16, 25, 36]), tensor([ 1,  4,  9, 16, 25, 36]))

In [2]:
x.pow(2) == x**2

tensor([True, True, True, True, True, True])

In [ ]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [5]:
x.dtype

torch.int64

In [6]:
type(x.float())

torch.Tensor

In [7]:
x.float().dtype

torch.float32

In [10]:
x.float().mean(-1)

tensor(3.5000)